CREATE TABLE `RANT` (
	`RANT_ID`	int	NOT NULL	COMMENT '도서 대출을 신청한 고유번호',
	`RANT_TIME`	varchar(10)	NOT NULL,
	`RETURN_TIME`	varchar(10)	NOT NULL,
	`RANT_COUN`	int	NOT NULL
);

CREATE TABLE `BOOK` (
	`BOOK_ID`	varchar(10)	NOT NULL	COMMENT '책의 고유번호',
	`BOOK_NAME`	varchar(50)	NOT NULL	COMMENT '책의 이름',
	`CALL_NUM`	varchar(15)	NOT NULL	COMMENT '숫자,문자로 표현',
	`FLOOR`	VARCHAR(5)	NOT NULL	COMMENT '책이 위치한 층수'
);

CREATE TABLE `RANT_BOOK` (
	`STUDENT_ID`	int	NOT NULL	COMMENT '학번(주키)',
	`NAME`	varchar(10)	NOT NULL	COMMENT '학생의 이름',
	`RANT_ID`	int	NOT NULL	COMMENT '도서 대출을 신청한 고유번호',
	`BOOK_ID`	varchar(10)	NOT NULL	COMMENT '책의 고유번호'
);

ALTER TABLE `RANT` ADD CONSTRAINT `PK_RANT` PRIMARY KEY (
	`RANT_ID`
);

ALTER TABLE `BOOK` ADD CONSTRAINT `PK_BOOK` PRIMARY KEY (
	`BOOK_ID`
);

ALTER TABLE `RANT_BOOK` ADD CONSTRAINT `PK_RANT_BOOK` PRIMARY KEY (
	`STUDENT_ID`
);

